# Generated by Django 4.2.6 on 2023-10-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Aluno',
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='Cidade',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Cursos',
        ),
    ]
